apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
spec:
  ports:
  - name: 32300-80
    port: 32300
    protocol: TCP
    targetPort: 80
  selector:
    app: vote
  type: NodePort
