apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
  namespace: instavote
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 30300
  selector:
    app: vote
  type: NodePort

