apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- deployment.yaml
- service.yaml
namespace: instavote
images:
- name: schoolofdevops/vote
  newTag: v4
replicas:
- name: vote
  count: 12
configMapGenerator:
  - name: cm_vote
    literals:
      - OPTION_A=STAGING
      - OPTION_B=DEV
