apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vote
  strategy: {}
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: schoolofdevops/vote:v3
        name: vote
        resources: {}
        env:
          - name: OPTION_A
            valueFrom:
              configMapKeyRef: 
                name: cm_vote
                key: OPTION_A
          - name: OPTION_B
            valueFrom:
              configMapKeyRef: 
                name: cm_vote
                key: OPTION_B
