apiVersion: apps/v1
kind: Deployment
metadata:
   creationTimestamp: null
   labels:
     app: vote
   name: vote
spec:
   minReadySeconds: 20
   replicas: 3
   template:
      spec:
        containers:
        - image: schoolofdevops/vote:v4
        name: vote
          env:
            - name: OPTION_A
              valueFrom:
                configMapKeyRef: 
                  name: cm-vote
                  key: OPTION_A
            - name: OPTION_B
              valueFrom:
                configMapKeyRef: 
                  name: cm-vote
                  key: OPTION_B
