apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- deployment.yaml
configMapGenerator:
  - name: cm-vote
    literals:
      - OPTION_A=WEBHOOK
      - OPTION_B=DEV
