apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- deployment.yaml
images:
- name: lauroffecapgemini/vote
  newTag: main-a42921bb-1664462735 # {"$imagepolicy": "flux-system:vote:tag"}
configMapGenerator:
- name: cm-vote
  literals:
  - OPTION_A=WEBHOOK
  - OPTION_B=DEV
